FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY Services/IdentityService/IdentityService.Api/IdentityService.Api.csproj ./Services/IdentityService/IdentityService.Api/
COPY Services/IdentityService/IdentityService.Logic/IdentityService.Logic.csproj ./Services/IdentityService/IdentityService.Logic/
COPY Services/IdentityService/IdentityService.Dal/IdentityService.Dal.csproj ./Services/IdentityService/IdentityService.Dal/
COPY Libs/CoreLib/CoreLib.csproj ./libs/CoreLib/
RUN dotnet restore ./Services/IdentityService/IdentityService.Api/IdentityService.Api.csproj

COPY . .
RUN dotnet publish ./Services/IdentityService/IdentityService.Api/IdentityService.Api.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "IdentityService.Api.dll"]
